In [1]:
import pandas as pd
import numpy as np

In [2]:
files = [
    "/content/IT Support Ticket Data.csv",
    "/content/customer_support_tickets_200k.csv",
    "/content/customer_support_tickets_200k.csv"
]

In [3]:
dfs = []
for f in files:
  temp_df = pd.read_csv(f)
  if "body" in temp_df.columns:
    temp_df = temp_df["body"]
  elif "issue_description" in temp_df.columns:
    temp_df = temp_df["issue_description"]
  elif "Body" in temp_df.columns:
    temp_df = temp_df["Body"]
  dfs.append(temp_df)

In [4]:
df = pd.concat(dfs, ignore_index = True)

In [5]:
df = df.to_frame(name = "description")

In [6]:
df.head(5)

                                         description
0  Dear Customer Support Team,I am writing to rep...
1  Dear Customer Support Team,I hope this message...
2  Dear Customer Support Team,I hope this message...
3  Dear Support Team,I hope this message reaches ...
4  Dear Customer Support,I hope this message reac...

In [7]:
df = df.dropna()

In [8]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [9]:
def clean_text(text, keep_punctuation=True, lemmatize=False, remove_stopwords=False):
    """
    Enhanced text cleaning with configurable options
    """
    original_text = text

    text = text.lower()

    text = re.sub(r"^(dear|hi|hello|hey)\s+.*?,", "", text, flags=re.IGNORECASE)

    polite_phrases = [
        r"i hope this message finds you well",
        r"i hope this message reaches you",
        r"i hope you are doing well",
        r"i am reaching out to",
        r"just writing to",
        r"i wanted to",
        r"i would like to",
        r"i am writing to (report|inform|ask|request)",
        r"please (find|see) attached",
        r"attached please find"
    ]

    for phrase in polite_phrases:
        text = re.sub(phrase, "", text, flags=re.IGNORECASE)

    signoffs = [
        r"thank you.*$", r"thanks.*$", r"regards.*$",
        r"best regards.*$", r"sincerely.*$", r"cheers.*$",
        r"appreciate your (help|assistance|time).*$",
        r"looking forward.*$"
    ]

    for signoff in signoffs:
        text = re.sub(signoff, "", text, flags=re.IGNORECASE)

    text = re.sub(r"\b\w+@\w+\.\w+\b", "", text)  # emails
    text = re.sub(r"\b\d{10,}\b", "", text)  # phone numbers
    text = re.sub(r"ticket\s*id:?\s*\w+", "", text, flags=re.IGNORECASE)  # ticket IDs

    if keep_punctuation:
        text = re.sub(r"[^\w\s\.\?\!]", "", text)
    else:
        text = re.sub(r"[^\w\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()

    if remove_stopwords or lemmatize:
        tokens = text.split()

        if remove_stopwords:
            stop_words = set(stopwords.words('english'))
            domain_words = {'not', 'no', 'but', 'however', 'issue', 'problem', 'error'}
            stop_words = stop_words - domain_words
            tokens = [word for word in tokens if word not in stop_words]

        if lemmatize:
            lemmatizer = WordNetLemmatizer()
            tokens = [lemmatizer.lemmatize(word) for word in tokens]

        text = ' '.join(tokens)

    if not text or len(text.split()) < 2:
        text = original_text.lower()
        text = re.sub(r"[^\w\s]", "", text)
        text = re.sub(r"\s+", " ", text).strip()

    return text

In [10]:
df["cleaned_text"] = df["description"].apply(clean_text)

In [11]:
df = df.drop_duplicates(subset=['cleaned_text'], keep='first')

print(f"Original rows: {len(df)}")
print(f"After dedup on cleaned_text: {len(df)}")

Original rows: 25047
After dedup on cleaned_text: 25047

In [12]:
df["cleaned_text"]

0        a significant problem with the centralized acc...
1        well. request detailed information about the c...
2        . request clarification about the billing and ...
3        well. ask about the compatibility of your prod...
4        in good health. i am eager to learn more about...
                               ...
29656    there seems to be a discrepancy in my billing ...
29657              request a refund for the recent charge.
29658    twofactor authentication codes are not being d...
29660    i am unable to access my account after enterin...
29662    i am experiencing very slow performance while ...
Name: cleaned_text, Length: 25047, dtype: object

In [13]:
%%capture
!pip install sentence-transformers

In [14]:
from sentence_transformers import SentenceTransformer
import torch

In [15]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [16]:
model_name = "all-mpnet-base-v2"

In [17]:
embedder = SentenceTransformer(model_name)
embedder.to(device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False, 'architecture': 'MPNetModel'})
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [18]:
texts = df["cleaned_text"].tolist()

In [19]:
embeddings = embedder.encode(
    texts,
    batch_size = 64,
    show_progress_bar = True,
    normalize_embeddings = True
)

Batches:   0%|          | 0/392 [00:00<?, ?it/s]

In [20]:
%%capture
!pip install cudf-cu12 cuml-cu12 --extra-index-url=https://pypi.nvidia.com

In [21]:
import cuml.cluster

In [22]:
import cuml

umap_model = cuml.UMAP(
    n_components=5,
    n_neighbors=15,
    min_dist=0.0,
    metric='cosine'
)
reduced_embeddings = umap_model.fit_transform(embeddings)

hdb = cuml.cluster.HDBSCAN(
    min_cluster_size=30,
    min_samples=1,
    metric='euclidean',
    cluster_selection_epsilon=0.1,
    cluster_selection_method='eom'
)
labels_gpu = hdb.fit_predict(reduced_embeddings)

In [23]:
n_clusters = len(np.unique(labels_gpu)) - (1 if -1 in labels_gpu else 0)
print(f"GPU HDBSCAN: {n_clusters} clusters")

GPU HDBSCAN: 162 clusters

In [24]:
unique, counts = np.unique(labels_gpu, return_counts=True)
n_clusters = len(unique) - (1 if -1 in unique else 0)
noise_count = counts[unique == -1][0] if -1 in unique else 0

print(f"Total clusters: {n_clusters}")
print(f"Noise / outliers: {noise_count} ({noise_count / len(labels_gpu) * 100:.1f}%)")
print(f"Largest 10 clusters sizes: {sorted(counts[unique != -1], reverse=True)[:10]}")
print(f"Small clusters (<20 tickets): {sum(counts < 20)}")

Total clusters: 162
Noise / outliers: 3269 (13.1%)
Largest 10 clusters sizes: [np.int64(2399), np.int64(1510), np.int64(1153), np.int64(825), np.int64(820), np.int64(546), np.int64(499), np.int64(489), np.int64(400), np.int64(382)]
Small clusters (<20 tickets): 0

In [25]:
import cuml
import cupy as cp

is_clustered = labels_gpu != -1
is_noise = labels_gpu == -1

knn = cuml.neighbors.KNeighborsClassifier(n_neighbors=1)
knn.fit(embeddings[is_clustered], labels_gpu[is_clustered])

noise_reassignments = knn.predict(embeddings[is_noise])

final_labels = labels_gpu.copy()
final_labels[is_noise] = noise_reassignments

noise_count = cp.sum(final_labels == -1)
print(f"Remaining noise: {noise_count}")

Remaining noise: 0

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

def get_cluster_keywords(texts, labels, n_words=10):
    df = pd.DataFrame({'text': texts, 'label': labels})
    docs_per_class = df.groupby(['label'], as_index=False).agg({'text': ' '.join})

    count = CountVectorizer(stop_words='english').fit(docs_per_class.text)
    t = count.transform(docs_per_class.text).toarray()
    w = t.sum(axis=1)
    tf = np.divide(t.T, w)
    sum_t = t.sum(axis=0)
    idf = np.log(np.divide(len(docs_per_class), sum_t, out=np.zeros_like(sum_t, dtype=float), where=sum_t!=0))
    tf_idf = np.multiply(tf.T, idf)

    words = count.get_feature_names_out()
    top_n_words = {label: [words[i] for i in tf_idf[i_label].argsort()[-n_words:]]
                   for i_label, label in enumerate(docs_per_class.label)}
    return top_n_words

keywords = get_cluster_keywords(texts, final_labels)

In [27]:
keywords

{0: ['computing',
  'deployments',
  'costeffectiveness',
  'savings',
  'instances',
  'costeffective',
  'ec2',
  'unnecessary',
  'instance',
  'expenses'],
 1: ['reflects',
  'adjustment',
  'expenses',
  'incurred',
  'spike',
  'clarifying',
  'correspondence',
  'correction',
  'months',
  'justify'],
 2: ['jam',
  'wirelessly',
  'paper',
  'printing',
  'print',
  'mobile',
  'duplex',
  'canon',
  'pixma',
  'mg3620'],
 3: ['ink',
  'jams',
  'print',
  'paper',
  'epson',
  'et4760',
  'ecotank',
  'hp',
  'deskjet',
  '3755'],
 4: ['internally',
  'onsite',
  'dropouts',
  'technician',
  'weeks',
  'drops',
  'routers',
  'networking',
  'isr4331',
  'enterprise'],
 5: ['tablet',
  'repair',
  '7s',
  'responsiveness',
  'k780',
  'touch',
  'surface',
  'keyboard',
  'detachable',
  'touchscreen'],
 6: ['assistancesincerely',
  'capabilitiesthank',
  'screenshots',
  '2019',
  'cases',
  'enhances',
  'manipulation',
  'alteryxs',
  'gained',
  'alteryx'],
 7: ['disclosing',
  'mcafee',
  'authorization',
  'repository',
  'red',
  'acknowledge',
  'committed',
  'receipt',
  'severity',
  'apache'],
 8: ['xb273k',
  'predator',
  'tv',
  'oled',
  'c1',
  '4k',
  'flickers',
  'brightness',
  'display',
  'flickering'],
 9: ['contactin',
  'synergize',
  'vide',
  'bitbucket',
  'rapidminers',
  'seeing',
  'desire',
  'deliverability',
  'sendgrids',
  'sendgrid'],
 10: ['returning',
  'activation',
  'life',
  'unopened',
  'order_num',
  'flickering',
  'charger',
  'charging',
  'battery',
  'm1'],
 11: ['lacks',
  'works',
  'opens',
  'automating',
  'automate',
  'optimally',
  'mailchimps',
  'synced',
  'knime',
  'mailchimp'],
 12: ['dropout',
  'exit',
  'career',
  'tripod',
  'interviews',
  'hires',
  'interactive',
  'tours',
  'guided',
  'onboarding'],
 13: ['alerts',
  'unpatched',
  'central',
  'alert',
  'monitored',
  'unauthorised',
  'probes',
  'tries',
  'bids',
  'unapproved'],
 14: ['overheat',
  'blue',
  'battery',
  'fan',
  'ultrabook',
  'overheating',
  'startup',
  'xps',
  '9310',
  'boot'],
 15: ['charging',
  'shop',
  'lenovo',
  'ultra',
  'chargers',
  'keyboard',
  's21',
  'ipad',
  'galaxy',
  'ideapad'],
 16: ['logging',
  'caching',
  'blocks',
  'pattern',
  'incognito',
  'discern',
  'logins',
  'friday',
  'morning',
  'cookies'],
 17: ['validating',
  'page',
  'logging',
  'busy',
  'ago',
  'hour',
  'durations',
  'timeout',
  'recurs',
  'contention'],
 18: ['github',
  'misplaced',
  'lts',
  'br1',
  'brbrthe',
  'activation',
  'debian',
  'raidcontroller',
  'library',
  'plus'],
 19: ['origin',
  'raidcontroller',
  'softwarerelated',
  'kingston',
  'datatraveler',
  'old',
  'webcam',
  'ms',
  'encrypt',
  'anomaly'],
 20: ['kits',
  '12',
  'trello',
  'xcode',
  'collection',
  'jenkins',
  'gnu',
  'compiler',
  'monday',
  'com'],
 21: ['promoted',
  'converting',
  'pitches',
  'hacking',
  'presentation',
  'ultimately',
  'automating',
  'departments',
  'compete',
  'toolkit'],
 22: ['site',
  'unexplained',
  'blocking',
  'engines',
  'dropped',
  'sharp',
  '50',
  'websites',
  'week',
  'keywords'],
 23: ['spending',
  'satisfactory',
  'modified',
  'unsatisfactory',
  'segments',
  'misaligned',
  'spend',
  'budgets',
  'demographics',
  'creatives'],
 24: ['audio',
  'sharing',
  'screensharing',
  'discussions',
  'cuts',
  'calls',
  '11',
  'conferencing',
  'conferences',
  'zoom'],
 25: ['suitability',
  'databases',
  'collection',
  'compiler',
  'gnu',
  'encrypting',
  'mint',
  'builtin',
  'auditing',
  'controlling'],
 26: ['transfer',
  '16port',
  'inaccessible',
  'tplink',
  'raid',
  'wlanrouter',
  'secured',
  'care',
  'denied',
  'denial'],
 27: ['grammarly',
  'photoshop',
  'clouds',
  'phrases',
  'readability',
  'sentences',
  'illustrator',
  'cc',
  'editor',
  'hemingway'],
 28: ['stores',
  'magento',
  'duo',
  'wix',
  'realigning',
  'western',
  'book',
  'magentos',
  'measurable',
  'shopify'],
 29: ['scikitlearn',
  'selection',
  'addons',
  'preparation',
  'interpretation',
  'combine',
  'powerful',
  'spss',
  'statistics',
  '28'],
 30: ['netgear',
  'smartwassermelder',
  'subject',
  'mesh',
  'mentions',
  'harnessed',
  'answer',
  'nighthawk',
  'smartgartenbewässerung',
  'bolster'],
 31: ['signatures',
  'red',
  '2019',
  'dynamics',
  'backing',
  'regulated',
  'onenote',
  'evernotes',
  'auditing',
  'chef'],
 32: ['partnerships',
  'sectors',
  'marketplace',
  'home',
  'hd',
  'near',
  'cameras',
  '6tb',
  'seagate',
  'sensor'],
 33: ['tk850',
  'benq',
  'u2720q',
  'nzxt',
  'pcs',
  'kraken',
  'z63',
  'partnerships',
  'gaming',
  'influencer'],
 34: ['codes',
  'phone',
  'twofactor',
  'delivered',
  'inquiries',
  'requiring',
  'alternatively',
  'proposed',
  'suits',
  'prefer'],
 35: ['descriptions',
  'enhances',
  'allows',
  'assignments',
  'shopware',
  'costrelated',
  'nest',
  'workspace',
  'joining',
  'schoology'],
 36: ['deals',
  'agreed',
  'promotional',
  'licensing',
  '99',
  'annual',
  'price',
  'renewal',
  'photoshop',
  '2024'],
 37: ['post',
  'cpu',
  'probe',
  'machines',
  'scanned',
  'upgraded',
  'inspected',
  'inspecting',
  'victim',
  'overheating'],
 38: ['reinforcing',
  'extent',
  'virus',
  'attack',
  'leak',
  'unsecured',
  'exposing',
  'posing',
  'unpatched',
  'suspicious'],
 39: ['relinking',
  'mismatches',
  'triggers',
  'smartküchengeräte',
  'reformat',
  'format',
  'signatures',
  'automate',
  'zapiers',
  'import'],
 40: ['pointed',
  'anticipation',
  'ecommerce',
  'lacks',
  'instruction',
  'mismatched',
  'chef',
  'light',
  'migration',
  'ring'],
 41: ['smarthomekamera',
  'nod32',
  'handled',
  'premium',
  'norton',
  'avast',
  'kaspersky',
  'plus',
  '360',
  'bitdefender'],
 42: ['pdffiller',
  'transfers',
  'expense',
  'signon',
  'paypal',
  'prospective',
  'exchanged',
  'larger',
  'ifttt',
  'accept'],
 43: ['differences',
  'relinking',
  'exports',
  'entering',
  'reauthenticate',
  'postupdate',
  'reestablish',
  'reconcile',
  'tokens',
  'manually'],
 44: ['jotting',
  'illustrate',
  'organize',
  'utilizes',
  'ulysses',
  'drawbacks',
  'airtables',
  'notetaking',
  'vagrant',
  'notes'],
 45: ['bradditionally',
  'considerations',
  'callback',
  'assurance',
  'gitlab',
  'ansible',
  'inmemory',
  'dockers',
  'containerization',
  'django'],
 46: ['documents',
  'works',
  'document',
  'confluence',
  'saasbased',
  'helps',
  'schoology',
  'signing',
  'docusign',
  'electronically'],
 47: ['priorities',
  'march',
  'prioritization',
  'sprint',
  'sprints',
  'ticket',
  'board',
  'boards',
  'tickets',
  'scrum'],
 48: ['uptime',
  'interconnected',
  'redacted',
  'concluded',
  '1045',
  'intensely',
  'upscaling',
  'toppriority',
  'tweaks',
  '30'],
 49: ['removing',
  'allocating',
  'brnotwithstanding',
  'brdespite',
  'page',
  'caching',
  'schema',
  'long',
  'real',
  'slowly'],
 50: ['individual',
  'highnetworth',
  'bi',
  'esg',
  'tableau',
  'investor',
  'choices',
  'institutions',
  'betterinformed',
  'investors'],
 51: ['editing',
  'implementations',
  'assessing',
  'attracted',
  'snippets',
  'typo3',
  'ulysses',
  '0s',
  'apache',
  'big'],
 52: ['annual',
  'subscribing',
  'contracts',
  'cycles',
  'bank',
  'accept',
  'paypal',
  'credit',
  'transfers',
  'cards'],
 53: ['notes',
  'research',
  'owner',
  'expense',
  'lookout',
  'organizing',
  'budgeting',
  'flow',
  'evernote',
  'cash'],
 54: ['virtualization',
  'common',
  'datarobots',
  'alongside',
  'consistency',
  'avoiding',
  'nosql',
  'wave',
  'cassandras',
  'pitfalls'],
 55: ['560x',
  'music',
  'laravel',
  'enjoys',
  'gb',
  '16',
  'cubase',
  'speed',
  'processor',
  'minimum'],
 56: ['verification',
  'advised',
  'requiring',
  'sectors',
  'strengthens',
  'mandating',
  'adoption',
  'onetime',
  'biometric',
  'multifactor'],
 57: ['prime',
  'attacks',
  'adopt',
  'multifactor',
  'necessity',
  'cyberattacks',
  'stronger',
  'personnel',
  'encrypting',
  'proactive'],
 58: ['misleading',
  'reoccurred',
  'outin',
  'mislead',
  'feeds',
  'frozen',
  'smartthermostat',
  'displaying',
  'displayed',
  'showing'],
 59: ['wellsuited',
  'ingestion',
  'querying',
  'mongodbs',
  'shard',
  'visualizing',
  'pipeline',
  'indexing',
  'pytorch',
  'aggregation'],
 60: ['disturbance',
  'portal',
  'division',
  'structural',
  'react',
  'javascript',
  'administration',
  'ticketing',
  'hr',
  'consultant'],
 61: ['partnership',
  'remote',
  'uptime',
  'experts',
  'flexible',
  'ticketing',
  'consultants',
  'consultation',
  'ticket',
  'administration'],
 62: ['reloaded',
  'coderelated',
  'function',
  'sites',
  'record',
  'ceased',
  'tracker',
  'websites',
  'codes',
  'tag'],
 63: ['ram',
  'realized',
  'bryour',
  'pinnacle',
  'disk',
  'froze',
  'stopping',
  'visualizations',
  'frozen',
  'freezing'],
 64: ['file',
  'word',
  'construct',
  'ought',
  'aidriven',
  'hyperparameters',
  'php',
  'ai',
  'h2o',
  'ais'],
 65: ['completion',
  'stabilize',
  'eclipse',
  '2024',
  'java',
  '202106',
  'refactoring',
  'ide',
  'idea',
  'intellij'],
 66: ['softwarehardware',
  'babbel',
  'quarterly',
  'evolved',
  'global',
  'currency',
  'maus',
  'hindrance',
  'rennlenkrad',
  'inflexible'],
 67: ['simplify',
  'specializes',
  'downgrades',
  'disjointed',
  'invoicing',
  'method',
  'priced',
  'competitively',
  'adjustment',
  'reminders'],
 68: ['asking',
  'cases',
  'effort',
  'asana',
  'inmemory',
  'deep',
  'outlines',
  'gems',
  'rediss',
  'play'],
 69: ['issued',
  'history',
  'billed',
  'items',
  'miscommunication',
  'contract',
  'unpaid',
  'inventory',
  'corrected',
  'overcharged'],
 70: ['requirement',
  'stored',
  'emphasize',
  'urge',
  'strongest',
  'introduce',
  'transmitting',
  'transmission',
  'act',
  'endtoend'],
 71: ['22',
  'avast',
  'premium',
  'pytorchs',
  'component',
  'posture',
  'central',
  'woocommerce',
  'typo3',
  'pytorch'],
 72: ['renewals',
  'switching',
  'gateway',
  'browsers',
  'gateways',
  'retrying',
  'locked',
  'recalculating',
  'overcharges',
  'portal'],
 73: ['mac',
  'mini',
  'ingestion',
  'nodes',
  'allocations',
  'resourceheavy',
  'expanded',
  'debian',
  'buster',
  'indexing'],
 74: ['executions',
  'consuming',
  'minority',
  'inoperative',
  'minute',
  'entreat',
  '14',
  'querying',
  'modem',
  'supportusers'],
 75: ['repository',
  'uploading',
  'pdffiller',
  'wordpress',
  'joystick',
  'gems',
  'dataintensive',
  'azures',
  'watch',
  'keras'],
 76: ['welche',
  'wenn',
  'schwierigkeiten',
  'würde',
  'optimierungstechniken',
  'türschloss',
  'purposes',
  'sie',
  'ich',
  'tensorflow'],
 77: ['postgresqls',
  'curiosity',
  'keenness',
  'joint',
  'strengths',
  'variety',
  'combination',
  'tutorial',
  'rapidminers',
  'rapidminer'],
 78: ['developer',
  'freeing',
  'restricts',
  'highvalue',
  'notetaking',
  'hubspot',
  'terraform',
  'books',
  'datarobot',
  'datarobots'],
 79: ['perspective',
  'combining',
  'advantages',
  'books',
  'drupals',
  'postproduction',
  'notions',
  'pdffiller',
  'notion',
  'nuendo'],
 80: ['ifttt',
  'speeds',
  'deleting',
  'inordinately',
  'sd',
  'slowly',
  'websites',
  'lexar',
  'switching',
  'images'],
 81: ['resonating',
  'personalized',
  'targeted',
  'reassess',
  'engage',
  'revamp',
  'templates',
  'reevaluate',
  'competitors',
  'innovative'],
 82: ['obligations',
  'straightforward',
  'distinctive',
  'characteristics',
  'simplification',
  'warranties',
  'points1',
  'possess',
  'easytofollow',
  'voicetotext'],
 83: ['revised',
  'regularly',
  'interaction',
  'stronger',
  'aiming',
  'technological',
  'superior',
  'elevate',
  'lines',
  'revise'],
 84: ['concentrating',
  'merging',
  'trouble',
  'asking',
  'compete',
  'supporting',
  'assessing',
  'unclear',
  'branding',
  'aesthetic'],
 85: ['means',
  'employ',
  'launches',
  'hi',
  'cubase',
  'promoting',
  'course',
  'steinberg',
  'promotion',
  'udemy'],
 86: ['agencies',
  'landscape',
  'topics',
  'footprint',
  'grow',
  'employs',
  'attract',
  'broader',
  'businesses',
  'measure'],
 87: ['combined',
  'collection',
  'proofreading',
  'effects',
  'cc',
  'firebases',
  'sign',
  'audition',
  'cyberlink',
  'firebase'],
 88: ['runs',
  'managers',
  'clickups',
  'tutorial',
  'hellosign',
  'activecampaigns',
  'projektor',
  'camtasia',
  'squarespace',
  'activecampaign'],
 89: ['overcome',
  'designing',
  'outlines',
  'fee',
  'ulysses',
  'smartlicht',
  'licensing',
  'xero',
  'component',
  'central'],
 90: ['frozen',
  'permission',
  'switching',
  'blocked',
  'reverted',
  'spikes',
  'factor',
  'freeze',
  'coinciding',
  'timeouts'],
 91: ['submissions',
  'scale',
  'lags',
  'latency',
  'page',
  'lag',
  'delayed',
  'amid',
  'concurrent',
  'heightened'],
 92: ['misstep',
  'thinkpad',
  'agreedupon',
  'reconciliation',
  'agreements',
  'transaction',
  'statement',
  'comparing',
  'vrcontroller',
  'overcharges'],
 93: ['overlapping',
  'history',
  'transaction',
  'renewal',
  'reconcile',
  'charged',
  'renewals',
  'twice',
  'statements',
  'duplicate'],
 94: ['reconnect',
  'disappearance',
  'doublechecked',
  'edits',
  'realign',
  'flawed',
  'reanalyze',
  'vanished',
  'codes',
  'tracked'],
 95: ['demand',
  'rising',
  'quote',
  'thinkpad',
  'debian',
  'pace',
  'growing',
  'carbon',
  'x1',
  'cope'],
 96: ['handles',
  'webhooks',
  'scaling',
  'growing',
  'accommodate',
  'aipowered',
  'expands',
  'architecture',
  'manages',
  'agile'],
 97: ['custom',
  'formats',
  'integrators',
  'limits',
  'manipulated',
  'oauth',
  'graphql',
  'developers',
  'endpoints',
  'sdks'],
 98: ['mop',
  'mopp',
  'smartthermometer',
  'lawn',
  'vacuum',
  'smarttracker',
  'roboter',
  'cleaning',
  'mowers',
  'robot'],
 99: ['meant',
  'excel',
  '70',
  'debug',
  'extensions',
  'spreadsheets',
  'powerpoint',
  'addins',
  'debugging',
  'pycharm'],
 100: ['demand',
  'surge',
  'timeouts',
  'indexes',
  'scale',
  'rise',
  'degradation',
  'busy',
  'balancing',
  'unoptimized'],
 101: ['simplified',
  'multilingual',
  'versatile',
  'facilitating',
  'executed',
  'timeconsuming',
  'likelihood',
  'translate',
  'inclusive',
  'languages'],
 102: ['connector',
  'waves',
  'projectors',
  'unsynchronized',
  'damaged',
  'view',
  'synchronize',
  'durations',
  '32',
  'automatically'],
 103: ['disk',
  'effects',
  'mx500',
  'secures',
  'davinci',
  'comes',
  'safeguarded',
  '2000',
  'kingston',
  'datatraveler'],
 104: ['storing',
  'securely',
  'mechanisms',
  'whitepapers',
  'compliant',
  'adhered',
  'adheres',
  'environments',
  'adhere',
  'certifications'],
 105: ['connectors',
  'gamingheadset',
  'external',
  'microservicesoriented',
  'vr',
  'prebuilt',
  'webhooks',
  'headsets',
  'brbradditionally',
  'sd'],
 106: ['enabling',
  'easier',
  'feasibility',
  'communicate',
  'workforce',
  'es500w',
  'desktop',
  'trackball',
  'whatsapp',
  'multidevice'],
 107: ['navigate',
  'filtering',
  'customizable',
  'userfriendly',
  'overwhelming',
  'confusing',
  'widgets',
  'layout',
  'intuitive',
  'navigation'],
 108: ['distinct',
  'licht',
  'smartroboterstaubsauger',
  'discord',
  'collect',
  'smartthermometer',
  'transferred',
  'smartrauchmelder',
  'smarttracker',
  'smartsheets'],
 109: ['gateways',
  'trial',
  'commitments',
  'corresponding',
  'structure',
  'demos',
  'purchases',
  'bulk',
  'tiers',
  'trials'],
 110: ['uninstalled',
  'sign',
  'docusign',
  'sd',
  'emails',
  'prestashop',
  'document',
  'lexar',
  'uninstalling',
  'signoff'],
 111: ['premiere',
  'conferencing',
  'effortlessly',
  'wastes',
  'highervalue',
  'labor',
  'ulysses',
  'international',
  'translate',
  'babbel'],
 112: ['onetime',
  'salesforce',
  'translator',
  'dynamics',
  'maple',
  'wave',
  'tenant',
  'sharepoint',
  'onedrive',
  'powerpoint'],
 113: ['nest',
  'uploads',
  'disconnection',
  'dream',
  'networking',
  'adapters',
  'aruba',
  'cloudbased',
  'networkrelated',
  '23'],
 114: ['quietcomfort',
  '35',
  'bose',
  'virtual',
  'webex',
  'hyperx',
  'recorder',
  'audio',
  'ii',
  'headset'],
 115: ['rectification',
  'scrutiny',
  'highbrightness',
  'alerting',
  'highluminosity',
  'supportbra',
  'succinct',
  'projector',
  'dispatched',
  'sequence'],
 116: ['libraries',
  'reestablishing',
  'clickups',
  'reconnect',
  'bitdefender',
  'accounting',
  'readily',
  'rechecking',
  'sage',
  'gitlab'],
 117: ['employee',
  'formatting',
  'generates',
  'validate',
  'addons',
  'import',
  'reupload',
  'rights',
  'lagging',
  'flagship'],
 118: ['precision',
  'eclipse',
  'standardize',
  'submission',
  'formats',
  'seeks',
  'evernote',
  'scanners',
  'format',
  'mismatches'],
 119: ['32',
  'morning',
  'disappearing',
  'perl',
  'lost',
  'dokumentenscanner',
  'recovering',
  'vanished',
  'backups',
  'disappeared'],
 120: ['outreach',
  'launching',
  'execution',
  'stalled',
  'inactive',
  'template',
  'come',
  'halted',
  'halt',
  'launch'],
 121: ['82',
  'twitch',
  'beta',
  'shortages',
  'restoring',
  'apologize',
  'characterized',
  'patience',
  'ccleaner',
  'monitored'],
 122: ['limiting',
  'patience',
  'queue',
  'validation',
  'apologize',
  'assigned',
  'imbalance',
  'misclassification',
  'unrelated',
  'reproduce'],
 123: ['browse',
  'hypothesized',
  'homepage',
  'coding',
  'malicious',
  'site',
  'scanned',
  'pinpointed',
  '102',
  'chrome'],
 124: ['rerouting',
  'site',
  'prevented',
  'revenue',
  'translation',
  'hinder',
  'hightraffic',
  'visitor',
  'disabled',
  'hosting'],
 125: ['highdefinition',
  'audition',
  'imac',
  'camera',
  'avid',
  '27',
  'obs',
  'rendering',
  'streaming',
  'premiere'],
 126: ['cooler',
  'thinkpad',
  'scanner',
  'peripheral',
  'carbon',
  'x1',
  'streamcam',
  'q300l',
  'master',
  'masterbox'],
 127: ['final',
  'inaccessibility',
  'coursera',
  'multiproduct',
  'obstructing',
  'modem',
  'execution',
  'productrelated',
  'hindered',
  'impeded'],
 128: ['anker',
  'usbc',
  'adapter',
  'netgear',
  'mesh',
  'ethernet',
  'cables',
  'units',
  'cm1000',
  'disconnections'],
 129: ['drives',
  'subtle',
  'projectors',
  'controller',
  'demonstration',
  'kit',
  'valve',
  'index',
  'vr',
  'reapplying'],
 130: ['leak',
  'esteemed',
  'indepth',
  'determining',
  'direction',
  'git',
  'improperly',
  'containers',
  'locked',
  'leaks'],
 131: ['recalibrating',
  'irregularities',
  'inconsistency',
  'crossverifying',
  'recalibrated',
  'calculations',
  'formulas',
  'rerun',
  'recalibrate',
  'generated'],
 132: ['abrupt',
  'resyncing',
  'tvs',
  'happen',
  'interfering',
  'monitors',
  'interfered',
  'mercurial',
  'babyphone',
  'usbstick'],
 133: ['reaction',
  'pipeline',
  'workloads',
  'workload',
  'pod',
  'redeploying',
  'cicd',
  'pods',
  'orchestration',
  'microservices'],
 134: ['manages',
  'teamwork',
  'supports',
  'mediumsized',
  'delegation',
  'customizations',
  'minibeamer',
  'fit',
  'duolingo',
  'assignment'],
 135: ['coms',
  'subversion',
  'webhooks',
  'sage',
  'lynda',
  'prebuilt',
  'trello',
  'fl',
  'ecommerce',
  'ableton'],
 136: ['precision',
  'asana',
  'dashcam',
  'brafter',
  'feeds',
  'pipelines',
  'connectors',
  'origins',
  'brcan',
  'raidcontroller'],
 137: ['happening',
  'interrupting',
  'concurrently',
  '82',
  'smartsicherheitskamera',
  'onenote',
  '15',
  'inputoutput',
  'os',
  'skype'],
 138: ['thankful',
  'recover',
  'freeing',
  'randomly',
  'relogin',
  'surfing',
  'brbrive',
  'brthe',
  'recurrent',
  'responses'],
 139: ['asset',
  'scenarios',
  'indication',
  'suboptimal',
  'fluctuations',
  'recalibrating',

In [28]:
import cupy as cp
import pandas as pd
from sklearn.cluster import AgglomerativeClustering


unique_labels = sorted([l for l in np.unique(final_labels) if l != -1])
centroids = cp.array([embeddings[final_labels == l].mean(axis=0) for l in unique_labels])

n_meta_clusters = 30
merger = AgglomerativeClustering(n_clusters=n_meta_clusters, metric='cosine', linkage='average')
meta_labels = merger.fit_predict(centroids.get())

cluster_to_meta_map = {old_idx: meta_idx for old_idx, meta_idx in zip(unique_labels, meta_labels)}

df['cluster_id'] = final_labels
df['meta_cluster_id'] = df['cluster_id'].map(cluster_to_meta_map)

df['meta_label_name'] = df['meta_cluster_id'].apply(lambda x: f"Meta-Group {x}")

In [29]:
df.head(5)

,description,cleaned_text,cluster_id,meta_cluster_id,meta_label_name
0,"Dear Customer Support Team,I am writing to rep...",a significant problem with the centralized acc...,121,0,Meta-Group 0
1,"Dear Customer Support Team,I hope this message...",well. request detailed information about the c...,32,10,Meta-Group 10
2,"Dear Customer Support Team,I hope this message...",. request clarification about the billing and ...,69,2,Meta-Group 2
3,"Dear Support Team,I hope this message reaches ...",well. ask about the compatibility of your prod...,21,10,Meta-Group 10
4,"Dear Customer Support,I hope this message reac...",in good health. i am eager to learn more about...,82,21,Meta-Group 21

In [30]:
df['meta_label_name'].value_counts()

meta_label_name
Meta-Group 0     5182
Meta-Group 28    3321
Meta-Group 14    3143
Meta-Group 10    3108
Meta-Group 5     2407
Meta-Group 8     2157
Meta-Group 6     1724
Meta-Group 2     1568
Meta-Group 9      301
Meta-Group 13     293
Meta-Group 7      169
Meta-Group 12     162
Meta-Group 11     160
Meta-Group 16     127
Meta-Group 19     125
Meta-Group 26     116
Meta-Group 20     115
Meta-Group 29     114
Meta-Group 3       98
Meta-Group 23      96
Meta-Group 25      89
Meta-Group 4       82
Meta-Group 22      78
Meta-Group 1       64
Meta-Group 17      52
Meta-Group 27      46
Meta-Group 21      44
Meta-Group 18      39
Meta-Group 24      36
Meta-Group 15      31
Name: count, dtype: int64

In [31]:
from collections import Counter

In [32]:
cluster_counts = Counter(labels_gpu)
sorted_clusters = sorted(cluster_counts.items(), key = lambda x: x[1], reverse = True)

In [33]:
cluster_counts = df["meta_cluster_id"].value_counts()
top_clusters = cluster_counts.index.sort_values()

for cid in top_clusters:
    if cid == -1: continue

    cluster_df = df[df["meta_cluster_id"] == cid]
    cluster_size = len(cluster_df)

    if cluster_size == 0:
        continue

    print(f"\n--- Meta-Group {cid} ({cluster_size} tickets) ---")

    samples = cluster_df["cleaned_text"].sample(
        min(5, cluster_size),
        random_state=42
    )

    for i, text in enumerate(samples, 1):
        preview = str(text).replace('\n', ' ').strip()
        print(f"  {i}. {preview[:180]}...")

--- Meta-Group 0 (5182 tickets) ---
  1. our saas system has encountered a freeze which has caused a loss of project data. this issue might be linked to the recent unifi software update or an hdmi cable problem. despite a...
  2. our marketing firm has encountered several failures during product integration likely due to software conflicts. we attempted to resolve the problem by rebooting systems and updati...
  3. have encountered sporadic access problems with the saas platform potentially due to recent server updates causing overload. initial diagnostics involved restarting servers and reve...
  4. noted a sharp decline in system performance during peak usage times. this might be due to a surge in user activity or inefficient queries. tried restarting the server and optimizin...
  5. i am contacting you to report an integration failure between monday.com and sap erp. it might be due to a mismatch in the api versions. i have already tried to resolve the issue by...

--- Meta-Group 1 (64 tickets) ---
  1. . i am facing a difficulty with querying the postgresql 14.3 database. it seems this issue is limited to a minority of user reports. although i have tried various troubleshooting t...
  2. hello we encountered severe data loss in mysql 8.0.30. immediate technical support is essential to recover the affected data promptly....
  3. customer support reports ongoing system outages impacting several interconnected products. the issue might be linked to the recent mysql 8.0 update which could be causing conflicts...
  4. mysql 8.0.30 repeatedly crashes. need immediate investigation to restore database uptime....
  5. customer support our company is experiencing ongoing service disruptions impacting docker mysql and zapier integrations. these outages are likely due to recent software updates tha...

--- Meta-Group 2 (1568 tickets) ---
  1. a highpriority incident pertaining to the aws management service. our business operations are adversely affected due to the current downtime experienced. this issue is causing subs...
  2. recently encountered an issue with the subscription payment which was declined. the problem might be due to insufficient funds or a card expiration. after verifying the card detail...
  3. facing billing irregularities on the saas platform. the issue might be due to recent software updates or configuration changes. after checking account settings and transaction logs...
  4. i am writing to seek information about the payment plans for digital marketing services. could you kindly provide me with details on the available options and their respective cost...
  5. an update to my billing details for optimized investment analytics tools and related product subscriptions to ensure uninterrupted service....

--- Meta-Group 3 (98 tickets) ---
  1. is there a way to get some insights on how to optimize sendgrid for better email marketing performance? i am looking to enhance my email campaigns and would greatly appreciate some...
  2. seeking advice on how to optimize sendgrid for better email marketing performance. i am interested in enhancing my email campaigns and would greatly appreciate guidance on how to b...
  3. i am keen to request an update to the existing mailchimp integration with adobe sign. currently the integration is not wellsuited for our automated customer engagement workflows. i...
  4. i am seeking detailed instructions on how to integrate sendgrids marketing automation features to support my brands growth strategies. i am interested in utilizing sendgrids functi...
  5. seeking to gather information for optimizing the sendgrid aws platform to enhance the effectiveness of our marketing campaigns. would appreciate insights and guidance on integratin...

--- Meta-Group 4 (82 tickets) ---
  1. i am seeking guidance on utilizing rapidminer for investment strategies and financial data analysis. could you provide comprehensive tutorial resources?...
  2. customer support team seeking guidance on integrating redis 6.2 saas platform through api. kindly provide comprehensive documentation and example usage to facilitate initial setup....
  3. customer support seeking detailed guidance on integrating rapidminer into our existing data analytics infrastructure. currently utilizing a combination of tools and would like to i...
  4. exploring possibility integrating rapidminer into current data analytics infrastructure. currently utilize a range of tools and platforms for managing and analyzing data. keen on l...
  5. kindly share comprehensive documentation on how to secure medical data utilizing redis version 6.2....

--- Meta-Group 5 (2407 tickets) ---
  1. information on the pricing for integrating blackboard learn with your saas project management service. could you kindly provide me with a comprehensive cost breakdown? additionally...
  2. i am requesting an enhancement to improve the applications compatibility and performance across various platforms such as ios and android. this would significantly enhance the user...
  3. would like to know about the latest updates and features in project management saas. i am eager to learn about the new tools and functionalities that have been recently added....
  4. integrating project timelines into a saas solution...
  5. seeking detailed information on integrating docker 20.10 into our project management saas platform. could you provide a breakdown of the necessary steps and point me to the relevan...

--- Meta-Group 6 (1724 tickets) ---
  1. seeking an enhancement of data analytics tools and hardware to improve investment analysis capabilities....
  2. we would like to request enhancements to the data analytics tools to optimize our investment strategies and improve our decisionmaking processes by providing detailed insights and ...
  3. i am seeking detailed information on data analytics solutions that can enhance investment optimization for financial firms. could you provide specific tools and techniques that you...
  4. tools such as tableau and power bi prove beneficial...
  5. seek enhancements to data analytics tools to improve investment optimization for better decisionmaking and financial strategies....

--- Meta-Group 7 (169 tickets) ---
  1. hello i am experiencing persistent wireless connection issues with my recently purchased epson ecotank et4760. request an exchange for this product as it has been problematic since...
  2. i am writing to bring to your attention an issue that ive been experiencing with my canon pixma mg3620 printer particularly related to wireless connectivity when setting it up on m...
  3. . i am writing to inquire about the features and the current availability of the epson ecotank et4760 printer in your online store. i have heard positive reviews regarding its perf...
  4. a persistent issue i am experiencing with my hp deskjet 3755 printer purchased from tech online store. every time i try to print more than one page the printer jams during the seco...
  5. i am facing consistent issues with the color print quality on my hp deskjet 3755. the prints are below expected standards and negatively impact my work. please assist in resolving ...

--- Meta-Group 8 (2157 tickets) ---
  1. is it possible to provide information on securing medical data at a hospital using your products? i would...
  2. respected customer support i am contacting you to seek information on the security strategies for utilizing discord in healthcare environments. given my role as a healthcare provid...
  3. seeking detailed information on the data security measures implemented for the services related to hospital products. specifically could you provide insights into the protocols and...
  4. we are in need of guidance to ensure the confidentiality integrity and availability of patients sensitive medical information at our hospital. we are seeking a reliable and efficie...
  5. hi im looking for guidance on how to secure medical data using microsoft windows 10 pro and microsoft dynamics 365. could you provide information on the security practices and feat...

--- Meta-Group 9 (301 tickets) ---
  1. i require assistance with the it consulting service specifically regarding software development and server administration. please advise on how we can quickly address this matter....
  2. we are facing a significant problem with server administration which is interrupting our ticketing system and software development activities. we need immediate support to address ...
  3. i am seeking beginnerlevel resources on software development best practices specifically focusing on server administration. could you please provide any guidelines or materials ava...
  4. . an evaluation and change of our current server administration process. we believe enhancing these protocols will result in more efficient operations and enhanced it solutions ove...
  5. require to boost server capacity to enhance performance for peak usage in the scalable saas project management platform....

--- Meta-Group 10 (3108 tickets) ---
  1. customer support reports that digital marketing campaigns managed by the agency did not meet expectations this quarter likely due to recent changes in platform algorithms. despite ...
  2. customer support requesting an update on the integration of digital strategy tools. the current configuration meets existing requirements but there is a desire to improve brand gro...
  3. i am writing to seek advice on the best digital approaches for boosting brand growth. in todays digital era maintaining a robust online footprint is essential for business competit...
  4. seeking information on digital strategy services for brand growth. interested in learning how these services can help a business expand its online presence and reach new customers....
  5. customer support could you please offer detailed digital strategy options to effectively boost brand growth? i am seeking ways to improve our online visibility and reach a broader ...

--- Meta-Group 11 (160 tickets) ---
  1. im experiencing a critical issue with jira software version 8.20. it seems there is a bug causing errors in our project management tasks and some queries fail to load entirely. thi...
  2. . i am writing to bring to your attention a critical issue we are experiencing with the slack application version 4.23.0. unfortunately users within our team are unable to receive ...
  3. client cant log in to jira software 8.20....
  4. documentation on how to integrate jira with cassandra 4.0 and adobe premiere pro 2021 for my current project. i have difficulties finding the right resources online. i would be ver...
  5. . im reaching out regarding an issue with missing ticket notifications in our instance of jira software 8.20. this problem is significantly impacting our project feedback and team ...

--- Meta-Group 12 (162 tickets) ---
  1. i hope this email finds you well. assistance with the ongoing project related to the ui design improvements of our existing react application. this project was initially developed ...
  2. could you please share your insights on the most effective methods for onboarding new users to our project management platform? i would greatly value any advice or materials that y...
  3. customer support is requesting an enhancement to user role permissions particularly for project management features. currently the permissions are limited which restricts effective...
  4. we are reaching out to request an adjustment in our sales strategies to better align with client feedback on project management features and usability. our current approach has rec...
  5. can you provide information on the best practices for onboarding new team members to the project management platform? i require guidance to help them get started quickly and effici...

--- Meta-Group 13 (293 tickets) ---
  1. facing occasional login difficulties which might be related to server overload during peak activity hours. even after enhancing server capabilities and refining the login procedure...
  2. issue observed sudden login failures for all users. possible cause database connection issue. actions taken restarted server verified firewall settings....
  3. lately users have been facing occasional login difficulties with the project management saas application. this might be because of server overload due to increased traffic. steps a...
  4. all users are encountering login difficulties. this might be related to the recent update or server congestion. despite attempts to restart the server and examine the logs the prob...
  5. we are facing a significant login challenge that is stopping users from accessing their accounts. this issue might be related to recent server updates. steps like restarting the se...

--- Meta-Group 14 (3143 tickets) ---
  1. the data analytics software for investments experienced an unexpected crash. despite rebooting updating and restarting pinnacle studio 24 the issue remains unresolved. it seems lik...
  2. i have noticed that the website analytics dashboard has suddenly stopped loading. despite restarting the server and reviewing the code for any errors the problem continues. potenti...
  3. the investment analysis tools are not responding which is affecting the optimization of decisionmaking possibly due to software conflicts from recent updates....
  4. customer support a system crash during data analysis has affected multiple products disrupting investment optimization efforts. the crash might be due to software incompatibility b...
  5. the investment forecasting model has encountered issues stemming from incorrect data analysis inputs....

--- Meta-Group 15 (31 tickets) ---
  1. . an upgrade for our current intellij idea installation to the latest version intellij idea 2024.1. we have been experiencing some limitations with our existing setup particularly ...
  2. intellij idea has experienced a crash which has disrupted my workflow. it could be due to outdated plugins or conflicting software versions. i have already restarted the ide and ch...
  3. a critical issue i have encountered with the intellij idea 2024.1 which is significantly impacting my project timeline. this matter is quite urgent as it is affecting our ability t...
  4. frequent crashes are happening with chef intellij idea 2021.1 on various devices likely due to compatibility issues....
  5. request to update the software for enhanced compatibility with the intellij idea toolset and improved performance and efficiency....

--- Meta-Group 16 (127 tickets) ---
  1. i am writing to express my concerns about the issue i am experiencing with my dell xps 13 9310. i purchased this laptop from tech online store on purchase_date and have encountered...
  2. communicate a problem ive encountered with my dell xps 13 laptop model 9310 which i bought a few months back from your store. lately i have observed that the screen flickers errati...
  3. i am experiencing power issues with my dell xps 13 9310. despite being fully charged the device refuses to turn on. kindly assist me with resolving this problem at your earliest co...
  4. im writing to request further details regarding the shipping and return policies for the dell xps 13 9310 ultrabook which i am planning to purchase from your tech online store. it ...
  5. a screen flickering issue i am experiencing with my dell xps 13 9310 laptop. the problem began recently and has persisted affecting the usability significantly. as this product is ...

--- Meta-Group 17 (52 tickets) ---
  1. . i have a few questions regarding zoom 5.11.0. firstly know the registration limits for largescale webinars using this version. additionally could you provide information on its s...
  2. i hope this email finds you well. my name is name and i am reaching out regarding an upgrade request for the zoom application that we currently have integrated within our it infras...
  3. . i am writing to bring to your attention certain connection issues we have encountered during webinars using zoom version 5.11.0. the participants experiencing these issues are pr...
  4. hello i am requesting help with configuring zoom version 5.11.0 and enabling screen sharing for webinars. please give me instructions on how to solve these issues at your earliest ...
  5. facing connectivity problems during zoom meetings....

--- Meta-Group 18 (39 tickets) ---
  1. merge tensorflow and red hat to boost decision support...
  2. optimize investments using tensorflow data analytics...
  3. seeking assistance with incorporating canvas tensorflow into digital marketing initiatives. can you supply comprehensive documentation or stepbystep tutorials?...
  4. i need assistance with integrating tensorflow into my ruby on rails project for data analytics. could you provide some resources or tutorials to help me get started?...
  5. i am interested in integrating tensorflow into our project management software. could you provide detailed information including any available guides or tutorials? i would greatly ...

--- Meta-Group 19 (125 tickets) ---
  1. we have been experiencing intermittent network disruptions potentially arising from misconfigurations in our cisco router isr4331. please investigate this issue and offer assistanc...
  2. im reaching out to report an issue weve been experiencing with our cisco router isr4331 in managing our enterprise networking needs. our organization has been encountering signific...
  3. notify you about a critical problem we faced with one of your devices during our standard operating hours. our cisco router isr4331 underwent an unanticipated reboot which led to a...
  4. i wish to escalate an issue we are currently facing with our cisco router isr4331. the connection drops out consistently severely impacting our operations. the router frequently di...
  5. an issue with the cisco router isr4331 that is experiencing sudden connectivity disruptions. the issue began affecting network performance across various departments causing signif...

--- Meta-Group 20 (115 tickets) ---
  1. . a customer name has contacted us regarding a responsiveness issue with their microsoft surface pro 7. please look into this matter and advise on the steps they should take to res...
  2. reporting connectivity problems with the logitech k780 keyboard. the issue arises when using different saas applications and i suspect it could be due to bluetooth interference or ...
  3. . i am writing to inquire about the availability and pricing of the microsoft surface pro 7 in your online store. i am specifically interested in the various configurations and any...
  4. to whom it may concern report a charging problem with my samsung galaxy tab s7. despite trying several different chargers it fails to charge. could you please help me resolve this ...
  5. we have been encountering display issues with the touchscreen monitors which are impacting the performance of our analytics software. this problem might be related to recent softwa...

--- Meta-Group 21 (44 tickets) ---
  1. which integrations are available?...
  2. could you please provide information on the integration options available?...
  3. request for easytofollow documentation on adding voicetotext functionality...
  4. is there any information on the integration options available?...
  5. could you please provide more details on how to integrate hellosign?...

--- Meta-Group 22 (78 tickets) ---
  1. seeking information on the process of integrating the zapier project management saas solution. would greatly appreciate any detailed guidance or resources that can help me get star...
  2. kindly supply the documentation for integrating saas mysql with zapier....
  3. hello i am seeking recommendations on how to use zapier with drupal commerce to enhance our digital marketing strategies. could you please provide some guidance?...

In [34]:
cluster_names = {
    'Meta-Group 0': 'Financial Data Analytics Support',
    'Meta-Group 1': 'System Outage & Service Disruption',
    'Meta-Group 2': 'General Technical Issues (Application & System Errors)',
    'Meta-Group 3': 'Documentation & Product Inquiries',
    'Meta-Group 4': 'Billing & Payment Issues',
    'Meta-Group 5': 'Third-Party Tools & Integration Requests',
    'Meta-Group 6': 'Service Downtime & Availability Issues',
    'Meta-Group 7': 'Application Functionality & Sync Issues',
    'Meta-Group 8': 'ClickUp Workflows & Integrations',
    'Meta-Group 9': 'Login & Access Issues',
    'Meta-Group 10': 'Security Software Integration & Setup',
    'Meta-Group 11': 'Digital Marketing Strategy & Performance',
    'Meta-Group 12': 'Collaboration Tools Connectivity & Hardware Issues',
    'Meta-Group 13': 'Email & Marketing Platform Integrations',
    'Meta-Group 14': 'Data & Analytics Platform Integrations Issues',
    'Meta-Group 15': 'IntelliJ IDEA Issues & Upgrades',
    'Meta-Group 16': 'Hardware Issues & Customer Support',
    'Meta-Group 17': 'AI & Analytics Tool Integrations',
    'Meta-Group 18': 'Jira Configuration & Support',
    'Meta-Group 19': 'General Support Requests',
    'Meta-Group 20': 'Redis Integration & Analytics',
    'Meta-Group 21': 'Network Connectivity & Router Issues',
    'Meta-Group 22': 'Zapier Integration & Workflow Automation',
    'Meta-Group 23': 'Printer Hardware & Connectivity Issues',
    'Meta-Group 24': 'Service & Subscription Information Requests',
    'Meta-Group 25': 'Data Security & Breach Mitigation',
    'Meta-Group 26': 'Consumer Hardware Issues & Purchase Support',
    'Meta-Group 27': 'Application & Software Stability Issues',
    'Meta-Group 28': 'Elasticsearch Integration & Analytics Optimization',
    'Meta-Group 29': 'Cloud & SaaS Integration Issues'
}

In [35]:
final_cluster_names = {
    'Meta-Group 0': 'Financial Data Analytics Support',
    'Meta-Group 1': 'Service Downtime & System Outages',
    'Meta-Group 2': 'Application & System Issues',
    'Meta-Group 3': 'Product & Documentation Inquiries',
    'Meta-Group 4': 'Billing & Payment Issues',
    'Meta-Group 5': 'Third-Party Tool Integrations',
    'Meta-Group 6': 'Service Downtime & System Outages',       # duplicate of 1
    'Meta-Group 7': 'Application Functionality & Sync Issues',
    'Meta-Group 8': 'Software & Platform Support',
    'Meta-Group 9': 'Login & Access Issues',
    'Meta-Group 10': 'Security Software Integration & Setup',
    'Meta-Group 11': 'Digital Marketing Strategy & Performance',
    'Meta-Group 12': 'Collaboration Tools Connectivity & Hardware Issues',
    'Meta-Group 13': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 14': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 15': 'Software & Platform Support',            # merged into 8
    'Meta-Group 16': 'Consumer Hardware Issues & Purchase Support',
    'Meta-Group 17': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 18': 'Software & Platform Support',            # merged into 8
    'Meta-Group 19': 'General Support Requests',
    'Meta-Group 20': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 21': 'Network Connectivity & Router Issues',
    'Meta-Group 22': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 23': 'Consumer Hardware Issues & Purchase Support', # merged into 16
    'Meta-Group 24': 'Billing & Payment Issues',               # merged into 4
    'Meta-Group 25': 'Security Software Integration & Setup',  # merged into 10
    'Meta-Group 26': 'Consumer Hardware Issues & Purchase Support', # merged into 16
    'Meta-Group 27': 'Application & System Issues',            # merged into 2
    'Meta-Group 28': 'Third-Party Tool Integrations',          # merged into 5
    'Meta-Group 29': 'Third-Party Tool Integrations'           # merged into 5
}

In [36]:
df["merged_category"] = df["meta_label_name"].map(final_cluster_names)

df["merged_category"] = df["merged_category"].fillna("Uncategorized / Rare Issues")

print(df["merged_category"].value_counts())

merged_category
Third-Party Tool Integrations                         9523
Financial Data Analytics Support                      5182
Security Software Integration & Setup                 3197
Software & Platform Support                           2227
Service Downtime & System Outages                     1788
Application & System Issues                           1614
Consumer Hardware Issues & Purchase Support            339
Login & Access Issues                                  301
Application Functionality & Sync Issues                169
Collaboration Tools Connectivity & Hardware Issues     162
Digital Marketing Strategy & Performance               160
General Support Requests                               125
Billing & Payment Issues                               118
Product & Documentation Inquiries                       98
Network Connectivity & Router Issues                    44
Name: count, dtype: int64

In [37]:
import json
with open("merged_cluster_names.json", "w") as f:
    json.dump(final_cluster_names, f, indent=2)

In [38]:
import pickle

with open('umap_model.pkl', 'wb') as f:
    pickle.dump(umap_model, f)

with open('knn_model.pkl', 'wb') as f:
    pickle.dump(knn, f)

with open('category_mapping.pkl', 'wb') as f:
    pickle.dump(final_cluster_names, f)

In [39]:
import re

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = " ".join(text.split())
    return text

def classify_new_ticket(ticket_text):
    clean_text = preprocess_text(ticket_text)

    new_embedding = embedder.encode([clean_text], normalize_embeddings=True)

    raw_pred = knn.predict(new_embedding)
    cluster_id = int(raw_pred[0])

    meta_id = cluster_to_meta_map.get(cluster_id, -1)
    key = f"Meta-Group {meta_id}"
    category = final_cluster_names.get(key, "Uncategorized")

    return category

In [40]:
clean = "Our latest campaign on Facebook is underperforming and the CPC is way too high. We need to re-evaluate the targeting."
print(f"Clean Result: {classify_new_ticket(clean)}")

Clean Result: Security Software Integration & Setup

In [41]:
import joblib

In [ ]:
joblib.dump(embeddings, 'best_embedding.joblib')

['best_embedding.joblib']

In [42]:
embedder.save('/content/embedder')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [44]:
import shutil
from google.colab import files

In [45]:
folder_to_zip = "/content/embedder"

output_zip = "/content/best_embedder"

shutil.make_archive(output_zip, 'zip', folder_to_zip)

'/content/best_embedder.zip'