In [ ]:
import pandas as pd
import numpy as np

In [ ]:
files = [
    "/content/IT Support Ticket Data.csv",
    "/content/customer_support_tickets_200k.csv",
]

In [ ]:
dfs = []
for f in files:
  temp_df = pd.read_csv(f)
  if "body" in temp_df.columns:
    temp_df = temp_df["body"]
  elif "issue_description" in temp_df.columns:
    temp_df = temp_df["issue_description"]
  elif "Body" in temp_df.columns:
    temp_df = temp_df["Body"]
  dfs.append(temp_df)

In [ ]:
df = pd.concat(dfs, ignore_index = True)

In [ ]:
df = df.to_frame(name = "description")

In [ ]:
df.head(5)

                                         description
0  Dear Customer Support Team,I am writing to rep...
1  Dear Customer Support Team,I hope this message...
2  Dear Customer Support Team,I hope this message...
3  Dear Support Team,I hope this message reaches ...
4  Dear Customer Support,I hope this message reac...

In [ ]:
df = df.dropna()

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
def clean_text(text, keep_punctuation=True, lemmatize=False, remove_stopwords=False):
    """
    Enhanced text cleaning with configurable options
    """
    original_text = text

    text = text.lower()

    text = re.sub(r"^(dear|hi|hello|hey)\s+.*?,", "", text, flags=re.IGNORECASE)

    polite_phrases = [
        r"i hope this message finds you well",
        r"i hope this message reaches you",
        r"i hope you are doing well",
        r"i am reaching out to",
        r"just writing to",
        r"i wanted to",
        r"i would like to",
        r"i am writing to (report|inform|ask|request)",
        r"please (find|see) attached",
        r"attached please find"
    ]

    for phrase in polite_phrases:
        text = re.sub(phrase, "", text, flags=re.IGNORECASE)

    signoffs = [
        r"thank you.*$", r"thanks.*$", r"regards.*$",
        r"best regards.*$", r"sincerely.*$", r"cheers.*$",
        r"appreciate your (help|assistance|time).*$",
        r"looking forward.*$"
    ]

    for signoff in signoffs:
        text = re.sub(signoff, "", text, flags=re.IGNORECASE)

    text = re.sub(r"\b\w+@\w+\.\w+\b", "", text)  # emails
    text = re.sub(r"\b\d{10,}\b", "", text)  # phone numbers
    text = re.sub(r"ticket\s*id:?\s*\w+", "", text, flags=re.IGNORECASE)  # ticket IDs

    if keep_punctuation:
        text = re.sub(r"[^\w\s\.\?\!]", "", text)
    else:
        text = re.sub(r"[^\w\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()

    if remove_stopwords or lemmatize:
        tokens = text.split()

        if remove_stopwords:
            stop_words = set(stopwords.words('english'))
            domain_words = {'not', 'no', 'but', 'however', 'issue', 'problem', 'error'}
            stop_words = stop_words - domain_words
            tokens = [word for word in tokens if word not in stop_words]

        if lemmatize:
            lemmatizer = WordNetLemmatizer()
            tokens = [lemmatizer.lemmatize(word) for word in tokens]

        text = ' '.join(tokens)

    if not text or len(text.split()) < 2:
        text = original_text.lower()
        text = re.sub(r"[^\w\s]", "", text)
        text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
df["cleaned_text"] = df["description"].apply(clean_text)

In [ ]:
df = df.drop_duplicates(subset=['cleaned_text'], keep='first')

print(f"Original rows: {len(df)}")
print(f"After dedup on cleaned_text: {len(df)}")

Original rows: 25047
After dedup on cleaned_text: 25047

In [ ]:
df["cleaned_text"]

0        a significant problem with the centralized acc...
1        well. request detailed information about the c...
2        . request clarification about the billing and ...
3        well. ask about the compatibility of your prod...
4        in good health. i am eager to learn more about...
                               ...
29656    there seems to be a discrepancy in my billing ...
29657              request a refund for the recent charge.
29658    twofactor authentication codes are not being d...
29660    i am unable to access my account after enterin...
29662    i am experiencing very slow performance while ...
Name: cleaned_text, Length: 25047, dtype: object

In [ ]:
df['cleaned_text'].to_csv("desc.csv", index = False)

In [ ]:
%%capture
!pip install sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer
import torch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
model_name = "BAAI/bge-large-en-v1.5"

In [ ]:
embedder = SentenceTransformer(model_name)
embedder.to(device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-large-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': True, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [ ]:
texts = df["cleaned_text"].tolist()

In [ ]:
embeddings = embedder.encode(
    texts,
    batch_size = 64,
    show_progress_bar = True,
    normalize_embeddings = True
)

Batches:   0%|          | 0/392 [00:00<?, ?it/s]

In [ ]:
%%capture
!pip install cudf-cu12 cuml-cu12 --extra-index-url=https://pypi.nvidia.com

In [ ]:
import cuml.cluster

In [ ]:
import cuml

umap_model = cuml.UMAP(
    n_components=5,
    n_neighbors=15,
    min_dist=0.0,
    metric='cosine'
)
reduced_embeddings = umap_model.fit_transform(embeddings)

hdb = cuml.cluster.HDBSCAN(
    min_cluster_size=30,
    min_samples=1,
    metric='euclidean',
    cluster_selection_epsilon=0.1,
    cluster_selection_method='eom'
)
labels_gpu = hdb.fit_predict(reduced_embeddings)

In [ ]:
!pip install lz4

Collecting lz4
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 36.2 MB/s eta 0:00:00
Installing collected packages: lz4
Successfully installed lz4-4.4.5

In [ ]:
import umap
import joblib
import numpy as np


embeddings_cpu = embeddings

cpu_umap = umap.UMAP(
    n_components=5,
    n_neighbors=15,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)
reduced_embeddings_cpu = cpu_umap.fit_transform(embeddings_cpu)

np.save("reduced_embeddings.npy", reduced_embeddings_cpu)
# joblib.dump(cpu_umap, "cpu_umap.pkl")
joblib.dump(cpu_umap, "cpu_umap_compressed.pkl", compress=('zlib', 3))


print(f"UMAP model saved. Reduced shape: {reduced_embeddings_cpu.shape}")

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

UMAP model saved. Reduced shape: (25047, 5)

In [ ]:
n_clusters = len(np.unique(labels_gpu)) - (1 if -1 in labels_gpu else 0)
print(f"GPU HDBSCAN: {n_clusters} clusters")

GPU HDBSCAN: 183 clusters

In [ ]:
unique, counts = np.unique(labels_gpu, return_counts=True)
n_clusters = len(unique) - (1 if -1 in unique else 0)
noise_count = counts[unique == -1][0] if -1 in unique else 0

print(f"Total clusters: {n_clusters}")
print(f"Noise / outliers: {noise_count} ({noise_count / len(labels_gpu) * 100:.1f}%)")
print(f"Largest 10 clusters sizes: {sorted(counts[unique != -1], reverse=True)[:10]}")
print(f"Small clusters (<20 tickets): {sum(counts < 20)}")

Total clusters: 183
Noise / outliers: 3858 (15.4%)
Largest 10 clusters sizes: [np.int64(738), np.int64(726), np.int64(587), np.int64(578), np.int64(555), np.int64(534), np.int64(444), np.int64(432), np.int64(423), np.int64(404)]
Small clusters (<20 tickets): 0

In [ ]:
import cuml
import cupy as cp

is_clustered = labels_gpu != -1
is_noise = labels_gpu == -1

knn = cuml.neighbors.KNeighborsClassifier(n_neighbors=1)
knn.fit(embeddings[is_clustered], labels_gpu[is_clustered])

noise_reassignments = knn.predict(embeddings[is_noise])

final_labels = labels_gpu.copy()
final_labels[is_noise] = noise_reassignments

noise_count = cp.sum(final_labels == -1)
print(f"Remaining noise: {noise_count}")

Remaining noise: 0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

def get_cluster_keywords(texts, labels, n_words=10):
    df = pd.DataFrame({'text': texts, 'label': labels})
    docs_per_class = df.groupby(['label'], as_index=False).agg({'text': ' '.join})

    count = CountVectorizer(stop_words='english').fit(docs_per_class.text)
    t = count.transform(docs_per_class.text).toarray()
    w = t.sum(axis=1)
    tf = np.divide(t.T, w)
    sum_t = t.sum(axis=0)
    idf = np.log(np.divide(len(docs_per_class), sum_t, out=np.zeros_like(sum_t, dtype=float), where=sum_t!=0))
    tf_idf = np.multiply(tf.T, idf)

    words = count.get_feature_names_out()
    top_n_words = {label: [words[i] for i in tf_idf[i_label].argsort()[-n_words:]]
                   for i_label, label in enumerate(docs_per_class.label)}
    return top_n_words

keywords = get_cluster_keywords(texts, final_labels)

In [ ]:
keywords

In [ ]:
import cupy as cp
import pandas as pd
from sklearn.cluster import AgglomerativeClustering


unique_labels = sorted([l for l in np.unique(final_labels) if l != -1])
centroids = cp.array([embeddings[final_labels == l].mean(axis=0) for l in unique_labels])

n_meta_clusters = 30
merger = AgglomerativeClustering(n_clusters=n_meta_clusters, metric='cosine', linkage='average')
meta_labels = merger.fit_predict(centroids.get())

cluster_to_meta_map = {old_idx: meta_idx for old_idx, meta_idx in zip(unique_labels, meta_labels)}

df['cluster_id'] = final_labels
df['meta_cluster_id'] = df['cluster_id'].map(cluster_to_meta_map)

df['meta_label_name'] = df['meta_cluster_id'].apply(lambda x: f"Meta-Group {x}")

In [ ]:
df.head(5)

,description,cleaned_text,cluster_id,meta_cluster_id,meta_label_name
0,"Dear Customer Support Team,I am writing to rep...",a significant problem with the centralized acc...,41,6,Meta-Group 6
1,"Dear Customer Support Team,I hope this message...",well. request detailed information about the c...,114,2,Meta-Group 2
2,"Dear Customer Support Team,I hope this message...",. request clarification about the billing and ...,31,23,Meta-Group 23
3,"Dear Support Team,I hope this message reaches ...",well. ask about the compatibility of your prod...,81,0,Meta-Group 0
4,"Dear Customer Support,I hope this message reac...",in good health. i am eager to learn more about...,126,2,Meta-Group 2

In [ ]:
df['meta_label_name'].value_counts()

meta_label_name
Meta-Group 6     4026
Meta-Group 10    3285
Meta-Group 4     3257
Meta-Group 0     2762
Meta-Group 2     2316
Meta-Group 12    2063
Meta-Group 11    1986
Meta-Group 3     1902
Meta-Group 23    1033
Meta-Group 8      453
Meta-Group 1      323
Meta-Group 9      284
Meta-Group 5      169
Meta-Group 18     161
Meta-Group 29     136
Meta-Group 25     113
Meta-Group 22     112
Meta-Group 19     109
Meta-Group 26      81
Meta-Group 20      64
Meta-Group 27      61
Meta-Group 13      57
Meta-Group 21      45
Meta-Group 17      39
Meta-Group 7       39
Meta-Group 28      39
Meta-Group 14      35
Meta-Group 16      34
Meta-Group 24      32
Meta-Group 15      31
Name: count, dtype: int64

In [ ]:
from collections import Counter

In [ ]:
cluster_counts = Counter(labels_gpu)
sorted_clusters = sorted(cluster_counts.items(), key = lambda x: x[1], reverse = True)

In [ ]:
cluster_counts = df["meta_cluster_id"].value_counts()
top_clusters = cluster_counts.index.sort_values()

for cid in top_clusters:
    if cid == -1: continue

    cluster_df = df[df["meta_cluster_id"] == cid]
    cluster_size = len(cluster_df)

    if cluster_size == 0:
        continue

    print(f"\n--- Meta-Group {cid} ({cluster_size} tickets) ---")

    samples = cluster_df["cleaned_text"].sample(
        min(10, cluster_size),
        random_state=42
    )

    for i, text in enumerate(samples, 1):
        preview = str(text).replace('\n', ' ').strip()
        print(f"  {i}. {preview[:180]}...")

--- Meta-Group 0 (2762 tickets) ---
  1. i am seeking guidance on how to integrate salesforce crm with digital marketing strategies. could you provide specific details on the benefits this integration brings to customers?...
  2. the level of engagement is below the anticipated threshold....
  3. customer support brwe are encountering difficulties with our marketing campaigns which are underperforming due to inconsistencies in our digital strategies. recent algorithm change...
  4. bring to your attention a sudden decrease in social media engagement. this might be related to the recent algorithm modifications. despite tweaking our strategies for targeting and...
  5. i am reporting that our digital marketing campaigns are being disrupted due to connectivity software problems. it appears that the issues originated from modem failure related to f...
  6. the marketing firm is experiencing a decline in brand growth through various digital strategies. this may be due to the use of outdated tools and ineffective campaigns. so far we h...
  7. facing difficulties in executing the marketing agencys digital strategy possibly due to conflicts between various listed products. attempts to resolve the issue by resetting device...
  8. hello we have noticed a sudden drop in our digital campaigns performance metrics. this could be due to recent changes in the platforms algorithms. we have already checked for any t...
  9. the digital marketing efforts by the agency have not performed as expected lately likely due to outdated tactics. initial modifications yielded limited results. we require expert s...
  10. i am contacting you to address an unexpected anomaly in our campaign analytics. after restarting our systems and reviewing our data sources the issue remains unresolved. i believe ...

--- Meta-Group 1 (323 tickets) ---
  1. a display flickering issue with my dell xps 13 9310 purchased from your online store. this problem occurs frequently making it difficult to use the laptop effectively. as the issue...
  2. greetings i am encountering problems with the battery of my new macbook air m1. the battery discharges rapidly and does not maintain a charge as anticipated. could you kindly provi...
  3. i am writing regarding ticket ticket_num for my dell xps 13 9310 which has encountered a frozen screen issue. despite attempting basic troubleshooting the problem persists. i would...
  4. request help regarding problems with my devices touchscreen monitor. lately the touchscreens responsiveness has become erratic making it difficult to navigate applications smoothly...
  5. i am experiencing an issue with my macbook air m1. despite fully charging the battery the device does not turn on. please advise on how to proceed with resolving this issue....
  6. request urgent technical support for my dell xps 13 9310 laptop as i am currently experiencing significant highperformance issues. the laptop is a critical tool for my daily tasks ...
  7. i am facing a recurring charging problem with my newly purchased iphone 13 pro from your online shop. the device does not charge reliably even after trying different chargers and o...
  8. i am writing to bring to your attention an issue ive encountered with my macbook air m1 which ive been experiencing intermittently since the latest macos update. i purchased this d...
  9. helloi am experiencing intermittent screen flickering on my macbook air m1 during video playback which affects usage. i have not made any recent changes to the system. could you pl...
  10. . i recently purchased a macbook air m1 from your online store and my order arrived a few days ago. the order number associated with this purchase is acc_num. while the transaction...

--- Meta-Group 2 (2316 tickets) ---
  1. we need to update the compatibility settings for various software and hardware to improve the integration within our project management saas platform and enhance overall performanc...
  2. customer support i am submitting a request to increase server capacity to optimize the database and improve scalability and performance for our saas project management platform. th...
  3. i am interested in saas project management tools and would like to understand the available billing options and payment methods. could you provide detailed information on various s...
  4. could you provide information on integrating saas gimp typo3?...
  5. customer support is seeking detailed instructions on how to integrate smartlight with airtable and mysql 8.0 for analytics workflows. could you please provide stepbystep tutorials ...
  6. may i request detailed documentation on saas scalability options subversion and oracle database 19c?...
  7. a significant enhancement to our internal human resources management system specifically targeting the user interface design and data analysis capabilities. despite the comprehensi...
  8. i require pricing information for teams utilizing several software integrations. could you give me more details?...
  9. please address the urgent need for an update to enhance compatibility with ios 15 and improve security features across affected products. this update is crucial to ensure seamless ...
  10. request to update the software for enhanced compatibility with the intellij idea toolset and improved performance and efficiency....

--- Meta-Group 3 (1902 tickets) ---
  1. we require enhancement in customer support and increased brand engagement across our affected products. the aim is to stay ahead of competitors and boost user interaction. could yo...
  2. customer support inquire about incorporating digital marketing tactics for our laser projector and vr headset products. could you offer guidance on effectively promoting these prod...
  3. looking to improve digital strategies by leveraging targeted marketing tools to boost brand growth across all our products and services urgently....
  4. would appreciate detailed information on digital strategy services to aid in brand growth. this will help in comprehending how these services can benefit our business....
  5. can you provide specifics on digital strategies that can enhance brand growth?...
  6. customer support seeking insights into digital strategies that can boost brand growth. would be grateful for a detailed explanation of the methods and techniques that can be employ...
  7. customer support inquire about the digital marketing strategies your company employs to enhance brand growth across various technology products. i am interested in the field and be...
  8. seeking assistance with the integration of digital marketing strategies into sap erp system....
  9. customer support seeking to understand digital marketing strategy packages that can aid in brand growth. would appreciate detailed information on the services offered and how they ...
  10. inquiring about digital strategies to promote the gamepad asus xonar ae. could you provide details on effective online marketing techniques social media campaigns influencer partne...

--- Meta-Group 4 (3257 tickets) ---
  1. customer support is compiling a report on a data security incident that affected the hospitals system and its medical data. the incident might have been due to outdated software or...
  2. customer support writing to inform you about a potential data breach at a healthcare provider. the breach has compromised medical records within hospital systems possibly due to ou...
  3. an unauthorized access attempt was detected on the hospitals system. it may have occurred due to a phishing attack. initial security measures have been implemented to monitor syste...
  4. customer support bra possible data breach has affected the security of medical data. vulnerabilities in the hospitals systems could have led to unauthorized access. initial checks ...
  5. unapproved access has been detected in the hospitals systems which may pose a risk to the medical data....
  6. there is a known risk of a data breach involving medical records that were accessed without authorization. this might be due to outdated security protocols. we have updated the ant...
  7. the healthcare providers system has been compromised potentially exposing medical data. it might have occurred due to outdated security protocols. passwords have been reviewed and ...
  8. an unauthorized access incident has compromised sensitive medical data within the hospital system. this may have resulted from a phishing attack targeting staff. passwords have bee...
  9. a medical data breach was identified. there was unauthorized access to patient records. a virus scan was conducted and firewall settings were reviewed....
  10. experienced unauthorized access alerts in medical data systems due to outdated software and weak passwords. updated the software and reinforced password policies but the issue stil...

--- Meta-Group 5 (169 tickets) ---
  1. hello i am contacting you to seek advice on how to integrate docker with your saas project management tool. my aim is to enhance the performance of my project and i believe docker ...
  2. seeking comprehensive api integration instructions for avast premium security within docker 20.10. i am interested in understanding the stepbystep procedures for connecting these t...
  3. seeking detailed information on integrating docker 20.10 into our project management saas. could you provide a comprehensive process necessary steps and any required documentation?...
  4. is it possible to get assistance with integrating postgresql 13 for investment data analytics tools? i am interested in leveraging the latest features of postgresql to enhance data...
  5. i am contacting you to inquire about integrating asana with redis 6.2 to enhance our investment data analytics. could you direct me to any resources or documentation that detail th...
  6. i am contacting you to inquire about integrating asana with redis 6.2 to enhance our investment data analytics. could you direct me to any resources or documentation on the best pr...
  7. i am reaching out for detailed documentation to integrate postgresql 13 into our scalable saas project management solution. could you provide stepbystep instructions to configure t...
  8. i am seeking comprehensive api integration instructions for avast premium security within docker version 20.10. i would like a stepbystep overview of the process to connect these t...
  9. is there any advice on how to integrate smartsheet with docker for project management? seeking guidance for a seamless integration to streamline the workflow....
  10. seeking support to optimize the integration of cassandra 4.0 with related applications. the current configuration is causing performance issues particularly affecting project manag...

--- Meta-Group 6 (4026 tickets) ---
  1. the agency faced service disruptions impacting several digital tools likely due to a recent software update or network instability....
  2. customer support reports frequent crashes and slow response times in the project management saas following the latest update. the team is investigating the problem and suspects it ...
  3. customers are facing delays in loading content because of high server usage....
  4. facing recurrent crashes with our scalable saas platform impacting several products. the issue might stem from incompatible software updates or resource allocation problems. steps ...
  5. users have reported occasional delays in response times within the project management saas. a recent database update might be the underlying cause. restarting services and clearing...
  6. facing occasional login difficulties which might be related to server overload during peak activity hours. even after enhancing server capabilities and refining the login procedure...
  7. we are experiencing sporadic data synchronization failures across several integrated applications. the problem might be caused by api overloads or network configuration mistakes. a...
  8. an unexpected system freeze happened while performing project updates which might be related to compatibility issues following recent software updates. restarting the compatibility...
  9. the saas platform stops functioning when creating a new project. i have restarted the server and reviewed the system logs but the issue remains unresolved....
  10. brbri am contacting you to report a problem with our api connection. when our system tried to connect to your api it did not work leading to a loss of data. upon investigation our ...

--- Meta-Group 7 (39 tickets) ---
  1. could you tell me what features are present in the most recent version?...
  2. could you please explain the services you provide?...
  3. request for api details...
  4. can we provide you with details?...
  5. could you inform me about the available features in the most recent iteration?...
  6. could you provide some information?...
  7. supply details about the features...
  8. seeking details...
  9. is it possible to get information on the services we offer?...
  10. could you provide more details?...

--- Meta-Group 8 (453 tickets) ---
  1. brbr you of a moderate priority issue that has arisen during the scheduled maintenance. an unexpected service interruption has had an impact on the infrastructure maintenance servi...
  2. inquire about the companys policies regarding remote work and flexible scheduling as a prospective employee. i am particularly interested in learning about the companys stance on w...
  3. i am writing to inquire about the it consulting service offerings and how they can benefit my general business needs. specifically understand more about the range of services you o...
  4. im seeking advice on optimizing our it infrastructure to support the growth of our small business. could you provide recommendations for enhancing efficiency? your guidance on best...
  5. i am writing to you regarding the upcoming scheduled maintenance of the aws services that were recently communicated. the advanced notification mentioned that the scheduled mainten...
  6. i hope this email finds you well. some adjustments in our aws management service settings. specifically were aiming to optimize our cost structure and enhance our current resource ...
  7. . i am writing to bring to your urgent attention a critical issue we are currently experiencing with our cloud infrastructure deployment specifically concerning your aws management...
  8. well. i am contacting you to request urgent assistance regarding an issue that has emerged during the frontend development of our react javascript application. this challenge is si...
  9. we are presently encountering a major problem with server management which is obstructing our ticketing system and software development efforts. prompt assistance is vital to resol...
  10. during peak traffic hours users frequently encounter disconnections. despite optimizing database queries and increasing server capacity the issues continue. a followup email from n...

--- Meta-Group 9 (284 tickets) ---
  1. request a detailed statement of billing payments for my recent acquisitions of hardware and software including peripheral devices and computers. these items are intended for health...
  2. about the subscription plans for integrating clickup with zapier and mongodb. could you please give me more information on the different plans and their costs? additionally i would...
  3. im writing to seek details on the payment conditions for digital strategy services. could you kindly furnish me with more information? it would be greatly appreciated if you could ...
  4. respected customer support team i am contacting you to seek information about the cost related to woocommerce integration. could you kindly furnish me with a comprehensive cost ana...
  5. customer support inquire about the billing details and payment options for pro tools and microsoft sql server 2019 licenses. could you please provide a comprehensive breakdown of t...
  6. i am writing to inquire about the payment methods for switch and matlab r2021a subscriptions. i am keen on purchasing a subscription but need to know which payment options are acce...
  7. i am looking to subscribe to multiple products. could you inform me about the payment options that are available? specifically can i make payments using a credit card or by bank tr...
  8. i am writing to seek information regarding the payment methods for switch and matlab r2021a subscriptions. i am keen on purchasing a subscription and would like to know which payme...
  9. customer support is reaching out to inquire about billing options and payment plans for the listed marketing services. could you please provide a detailed cost breakdown for these ...
  10. greetings customer support details on the payment methods that are compatible with integrating magento into your saas platform. i am eager to learn about the diverse payment gatewa...

--- Meta-Group 10 (3285 tickets) ---
  1. noted the inconsistencies in the investment performance reports generated by the data analytics platform. these discrepancies might have arisen due to recent software updates that ...
  2. the application experienced a crash during data processing due to compatibility problems....
  3. facing connectivity challenges with cisco webex meetings which are disrupting investment analytics meetings following recent network adjustments on the ubiquiti unifi dream machine...
  4. the investment analysis platform is producing inconsistent data outputs which may be due to potential software integration issues. steps taken to resolve the issue such as rebootin...
  5. we have observed inconsistencies in the data analytics reports. these discrepancies might be due to recent software updates. even after rerunning the reports and verifying the data...
  6. facing difficulties with the accuracy of data analytics which is impacting the optimization of investments due to recent software updates and data integration issues....
  7. while generating the report for the data analytics tool the tool crashed unexpectedly preventing user access. the crash might be due to insufficient memory from the hyperx fury 32g...
  8. the organization is experiencing performance issues across various systems including macos vpn sap and analytics platforms possibly due to network congestion. initial troubleshooti...
  9. data analysis was interrupted following the software update. efforts to restart or reinstall the software have been unsuccessful....
  10. facing data synchronization challenges across various platforms which is affecting investment analysis. could be related to recent software updates or network instability. tried re...

--- Meta-Group 11 (1986 tickets) ---
  1. customer support i am inquiring about integrating sage accounting with python 3.9 to enhance investment data analytics. i would greatly appreciate any guidance on this matter as i ...
  2. enhancements to the investment data analytics platform. as a valued customer i believe that improving portfolio optimization and decisionmaking efficiency is essential for our busi...
  3. i am contacting you to seek information about data analytics solutions that can be integrated with quickbooks online for the purpose of investment optimization. could you supply me...
  4. i am seeking data analytics tools to optimize my investment portfolios for achieving high returns. could you recommend any tools or services that could assist me in this endeavor?...
  5. customer support seeking information on how data analytics solutions can optimize investment strategies. would like to know what types of analytics tools are available that can ass...
  6. request an enhancement in the integration of our data analytics tools with salesforce crm. currently the integration is limited and does not provide the level of detail required fo...

In [ ]:
cluster_names = {
    'Meta-Group 0': 'Digital Marketing Performance Issues',
    'Meta-Group 1': 'End-User Device Issues',
    'Meta-Group 2': 'System Configuration & Integration Issues',
    'Meta-Group 3': 'Marketing Strategy Requests',
    'Meta-Group 4': 'Data Breach & Unauthorized Access Incidents',
    'Meta-Group 5': 'Integration & API Requests',
    'Meta-Group 6': 'System Performance & Availability Issues',
    'Meta-Group 7': 'Product & Service Information Requests',
    'Meta-Group 8': 'Infrastructure & Operational Issues',
    'Meta-Group 9': 'Billing & Payment Inquiries',
    'Meta-Group 10': 'Data Processing & Reporting Issues',
    'Meta-Group 11': 'Investment Analytics & Optimization Requests',
    'Meta-Group 12': 'Data Security & Compliance Guidance',
    'Meta-Group 13': 'Analytics Tracking & Dashboard Issues',
    'Meta-Group 14': 'Billing Errors & Invoice Discrepancies',
    'Meta-Group 15': 'Database Performance & Connectivity Issues',
    'Meta-Group 16': 'Integration Requests (Project Management Tools)',
    'Meta-Group 17': 'Analytics Tools Integration & Usage Issues',
    'Meta-Group 18': 'Peripheral Device Issues (Printers & Accessories)',
    'Meta-Group 19': 'Application Usage & Configuration Issues',
    'Meta-Group 20': 'Network & Connectivity Issues',
    'Meta-Group 21': 'Analytics Tools & Integration Guidance',
    'Meta-Group 22': 'Security Tools Setup & Usage Guidance',
    'Meta-Group 23': 'Billing Errors & Payment Issues',
    'Meta-Group 24': 'Search & Indexing System Issues',
    'Meta-Group 25': 'Encryption & Data Protection Issues',
    'Meta-Group 26': 'System Requirements & Compatibility Guidance',
    'Meta-Group 27': 'General Assistance Requests',
    'Meta-Group 28': 'Integration & Implementation Instructions',
    'Meta-Group 29': 'Network & Router Connectivity Issues'
}

In [ ]:
import json

with open("meta_cluster_names.json", "w") as f:
  json.dump(cluster_names, f)

In [ ]:

final_cluster_names = {
    "Meta-Group 0": "Marketing & Digital Strategy",
    "Meta-Group 1": "Hardware & End-User Devices",
    "Meta-Group 2": "System Configuration & Integration",
    "Meta-Group 3": "Marketing & Digital Strategy",
    "Meta-Group 4": "Data Security & Compliance",
    "Meta-Group 5": "System Configuration & Integration",
    "Meta-Group 6": "System Performance & Availability",
    "Meta-Group 7": "Product & Service Information",
    "Meta-Group 8": "System Performance & Availability",
    "Meta-Group 9": "Billing, Payments & Subscriptions",
    "Meta-Group 10": "System Performance & Availability",
    "Meta-Group 11": "Financial Analytics & Investment Insights",
    "Meta-Group 12": "Data Security & Compliance",
    "Meta-Group 13": "System Performance & Availability",
    "Meta-Group 14": "Billing, Payments & Subscriptions",
    "Meta-Group 15": "System Performance & Availability",
    "Meta-Group 16": "System Configuration & Integration",
    "Meta-Group 17": "System Configuration & Integration",
    "Meta-Group 18": "Hardware & End-User Devices",
    "Meta-Group 19": "System Configuration & Integration",
    "Meta-Group 20": "Network & Connectivity",
    "Meta-Group 21": "System Configuration & Integration",
    "Meta-Group 22": "Data Security & Compliance",
    "Meta-Group 23": "Billing, Payments & Subscriptions",
    "Meta-Group 24": "System Performance & Availability",
    "Meta-Group 25": "Data Security & Compliance",
    "Meta-Group 26": "System Configuration & Integration",
    "Meta-Group 27": "General Assistance",
    "Meta-Group 28": "System Configuration & Integration",
    "Meta-Group 29": "Network & Connectivity"
  }

In [ ]:
import json

with open("final_cluster_names.json", "w") as f:
  json.dump(final_cluster_names, f)

In [ ]:
df["merged_category"] = df["meta_label_name"].map(final_cluster_names)

df["merged_category"] = df["merged_category"].fillna("Uncategorized / Rare Issues")

print(df["merged_category"].value_counts())

merged_category
System Performance & Availability            7884
Data Security & Compliance                   5545
Marketing & Digital Strategy                 4664
System Configuration & Integration           2832
Financial Analytics & Investment Insights    1986
Billing, Payments & Subscriptions            1352
Hardware & End-User Devices                   484
Network & Connectivity                        200
General Assistance                             61
Product & Service Information                  39
Name: count, dtype: int64

In [ ]:
import json
with open("merged_cluster_names.json", "w") as f:
    json.dump(final_cluster_names, f, indent=2)

In [ ]:
import pickle

with open('umap_model.pkl', 'wb') as f:
    pickle.dump(umap_model, f)

with open('knn_model.pkl', 'wb') as f:
    pickle.dump(knn, f)

with open('category_mapping.pkl', 'wb') as f:
    pickle.dump(final_cluster_names, f)

In [ ]:
import re

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = " ".join(text.split())
    return text

def classify_new_ticket(ticket_text):
    clean_text = preprocess_text(ticket_text)

    new_embedding = embedder.encode([clean_text], normalize_embeddings=True)

    raw_pred = knn.predict(new_embedding)
    cluster_id = int(raw_pred[0])

    meta_id = cluster_to_meta_map.get(cluster_id, -1)
    key = f"Meta-Group {meta_id}"
    category = final_cluster_names.get(key, "Uncategorized")

    return category

In [ ]:
clean = "Customer suggests adding dark mode to improve usability at night."
print(f"Clean Result: {classify_new_ticket(clean)}")

Clean Result: System Configuration & Integration

In [ ]:
import joblib

In [ ]:
joblib.dump(embeddings, 'best_embeddings.joblib')

['best_embeddings.joblib']

In [ ]:
import numpy as np
np.save("embeddings.npy", embeddings)

In [ ]:
df

,description,cleaned_text,cluster_id,meta_cluster_id,meta_label_name,merged_category
0,"Dear Customer Support Team,I am writing to rep...",a significant problem with the centralized acc...,41,6,Meta-Group 6,System Performance & Availability
1,"Dear Customer Support Team,I hope this message...",well. request detailed information about the c...,114,2,Meta-Group 2,System Configuration & Integration
2,"Dear Customer Support Team,I hope this message...",. request clarification about the billing and ...,31,23,Meta-Group 23,"Billing, Payments & Subscriptions"
3,"Dear Support Team,I hope this message reaches ...",well. ask about the compatibility of your prod...,81,0,Meta-Group 0,Marketing & Digital Strategy
4,"Dear Customer Support,I hope this message reac...",in good health. i am eager to learn more about...,126,2,Meta-Group 2,System Configuration & Integration
...,...,...,...,...,...,...
29656,There seems to be a discrepancy in my billing ...,there seems to be a discrepancy in my billing ...,43,14,Meta-Group 14,"Billing, Payments & Subscriptions"
29657,I would like to request a refund for the recen...,request a refund for the recent charge.,66,23,Meta-Group 23,"Billing, Payments & Subscriptions"
29658,Two-factor authentication codes are not being ...,twofactor authentication codes are not being d...,158,6,Meta-Group 6,System Performance & Availability
29660,I am unable to access my account after enterin...,i am unable to access my account after enterin...,42,6,Meta-Group 6,System Performance & Availability
29662,I am experiencing very slow performance while ...,i am experiencing very slow performance while ...,157,6,Meta-Group 6,System Performance & Availability

In [ ]:
np.save("meta_cluster_ids.npy", df["meta_cluster_id"].values)

df["merged_category"].to_csv("merged_category.csv", index=False)

In [ ]:
desc = pd.read_csv("/content/desc.csv")
cats = pd.read_csv("/content/merged_category.csv")

In [ ]:
desc

                                            cleaned_text
0      a significant problem with the centralized acc...
1      well. request detailed information about the c...
2      . request clarification about the billing and ...
3      well. ask about the compatibility of your prod...
4      in good health. i am eager to learn more about...
...                                                  ...
25042  there seems to be a discrepancy in my billing ...
25043            request a refund for the recent charge.
25044  twofactor authentication codes are not being d...
25045  i am unable to access my account after enterin...
25046  i am experiencing very slow performance while ...

[25047 rows x 1 columns]

In [ ]:
cats

                          merged_category
0       System Performance & Availability
1      System Configuration & Integration
2       Billing, Payments & Subscriptions
3            Marketing & Digital Strategy
4      System Configuration & Integration
...                                   ...
25042   Billing, Payments & Subscriptions
25043   Billing, Payments & Subscriptions
25044   System Performance & Availability
25045   System Performance & Availability
25046   System Performance & Availability

[25047 rows x 1 columns]

In [ ]:
desc['category'] = cats["merged_category"]

In [ ]:
desc.rename(columns = {'cleaned_text': 'description'}, inplace = True)

In [ ]:
desc.to_csv("desc_cats.csv", index = False)

In [ ]:
descats = pd.read_csv('/content/desc_cats.csv')

In [ ]:
descats[272:273]

,description,category
272,we are encountering a failure in vpnrouter con...,System Performance & Availability

In [ ]:
from sklearn.neural_network import MLPRegressor
import joblib


surrogate = MLPRegressor(
    hidden_layer_sizes=(256, 128),
    activation='relu',
    max_iter=200,
    random_state=42,
    verbose=True
)
surrogate.fit(embeddings_cpu, reduced_embeddings_cpu)


sample = surrogate.predict(embeddings_cpu[:5])
print("Output shape:", sample.shape)

joblib.dump(surrogate, "umap_surrogate.joblib")
print("Surrogate saved")

Iteration 1, loss = 2.04056287
Iteration 2, loss = 0.44270492
Iteration 3, loss = 0.32296327
Iteration 4, loss = 0.26782569
Iteration 5, loss = 0.23376045
Iteration 6, loss = 0.20964478
Iteration 7, loss = 0.18922636
Iteration 8, loss = 0.17243937
Iteration 9, loss = 0.15759495
Iteration 10, loss = 0.14637116
Iteration 11, loss = 0.13504747
Iteration 12, loss = 0.12439672
Iteration 13, loss = 0.11801883
Iteration 14, loss = 0.10960852
Iteration 15, loss = 0.10160699
Iteration 16, loss = 0.09572732
Iteration 17, loss = 0.08986752
Iteration 18, loss = 0.08557455
Iteration 19, loss = 0.08019896
Iteration 20, loss = 0.07556412
Iteration 21, loss = 0.07296162
Iteration 22, loss = 0.06838433
Iteration 23, loss = 0.06439127
Iteration 24, loss = 0.06177592
Iteration 25, loss = 0.05884020
Iteration 26, loss = 0.05659054
Iteration 27, loss = 0.05430194
Iteration 28, loss = 0.05234285
Iteration 29, loss = 0.04836779
Iteration 30, loss = 0.04667997
Iteration 31, loss = 0.04495201
Iteration 32, loss = 0.04350274
Iteration 33, loss = 0.04148617
Iteration 34, loss = 0.03997150
Iteration 35, loss = 0.03881658
Iteration 36, loss = 0.03681805
Iteration 37, loss = 0.03518049
Iteration 38, loss = 0.03442043
Iteration 39, loss = 0.03306527
Iteration 40, loss = 0.03231048
Iteration 41, loss = 0.03047168
Iteration 42, loss = 0.03062744
Iteration 43, loss = 0.02874031
Iteration 44, loss = 0.02795428
Iteration 45, loss = 0.02687033
Iteration 46, loss = 0.02625136
Iteration 47, loss = 0.02570907
Iteration 48, loss = 0.02552292
Iteration 49, loss = 0.02400320
Iteration 50, loss = 0.02371134
Iteration 51, loss = 0.02304701
Iteration 52, loss = 0.02248037
Iteration 53, loss = 0.02208452
Iteration 54, loss = 0.02111035
Iteration 55, loss = 0.02100136
Iteration 56, loss = 0.02075325
Iteration 57, loss = 0.01961166
Iteration 58, loss = 0.01906051
Iteration 59, loss = 0.01918848
Iteration 60, loss = 0.01854244
Iteration 61, loss = 0.01829002
Iteration 62, loss = 0.01773281
Iteration 63, loss = 0.01764773
Iteration 64, loss = 0.01698192
Iteration 65, loss = 0.01699610
Iteration 66, loss = 0.01657958
Iteration 67, loss = 0.01622525
Iteration 68, loss = 0.01600646
Iteration 69, loss = 0.01544675
Iteration 70, loss = 0.01528156
Iteration 71, loss = 0.01531551
Iteration 72, loss = 0.01445450
Iteration 73, loss = 0.01481656
Iteration 74, loss = 0.01384135
Iteration 75, loss = 0.01390812
Iteration 76, loss = 0.01354554
Iteration 77, loss = 0.01379954
Iteration 78, loss = 0.01321584
Iteration 79, loss = 0.01334542
Iteration 80, loss = 0.01312224
Iteration 81, loss = 0.01264155
Iteration 82, loss = 0.01339362
Iteration 83, loss = 0.01241600
Iteration 84, loss = 0.01221206
Iteration 85, loss = 0.01233480
Iteration 86, loss = 0.01207594
Iteration 87, loss = 0.01181481
Iteration 88, loss = 0.01175454
Iteration 89, loss = 0.01097532
Iteration 90, loss = 0.01134562
Iteration 91, loss = 0.01113978
Iteration 92, loss = 0.01095225
Iteration 93, loss = 0.01070860
Iteration 94, loss = 0.01070374
Iteration 95, loss = 0.01041896
Iteration 96, loss = 0.01074144
Iteration 97, loss = 0.01041752
Iteration 98, loss = 0.01007613
Iteration 99, loss = 0.01020338
Iteration 100, loss = 0.01021391
Iteration 101, loss = 0.01011638
Iteration 102, loss = 0.00979003
Iteration 103, loss = 0.00993066
Iteration 104, loss = 0.00965645
Iteration 105, loss = 0.00927971
Iteration 106, loss = 0.00930428
Iteration 107, loss = 0.00937434
Iteration 108, loss = 0.00935165
Iteration 109, loss = 0.00950594
Iteration 110, loss = 0.00915526
Iteration 111, loss = 0.00886084
Iteration 112, loss = 0.00857842
Iteration 113, loss = 0.00867194
Iteration 114, loss = 0.00912981
Iteration 115, loss = 0.00878519
Iteration 116, loss = 0.00853118
Iteration 117, loss = 0.00855822
Iteration 118, loss = 0.00840673
Iteration 119, loss = 0.00835820
Iteration 120, loss = 0.00894680
Iteration 121, loss = 0.00814528
Iteration 122, loss = 0.00811217
Iteration 123, loss = 0.00822608
Iteration 124, loss = 0.00827946
Iteration 125, loss = 0.00822808
Iteration 126, loss = 0.00804170
Iteration 127, loss = 0.00775503
Iteration 128, loss = 0.00776366
Iteration 129, loss = 0.00797173
Iteration 130, loss = 0.00780078
Iteration 131, loss = 0.00790548
Iteration 132, loss = 0.00777803
Iteration 133, loss = 0.00767143
Iteration 134, loss = 0.00750627
Iteration 135, loss = 0.00729986
Iteration 136, loss = 0.00764569
Iteration 137, loss = 0.00744923
Iteration 138, loss = 0.00715343
Iteration 139, loss = 0.00734129
Iteration 140, loss = 0.00719578
Iteration 141, loss = 0.00730732
Iteration 142, loss = 0.00711531
Iteration 143, loss = 0.00742203
Iteration 144, loss = 0.00691941
Iteration 145, loss = 0.00693023
Iteration 146, loss = 0.00707466
Iteration 147, loss = 0.00679494
Iteration 148, loss = 0.00687281
Iteration 149, loss = 0.00678939
Iteration 150, loss = 0.00691866
Iteration 151, loss = 0.00697661
Iteration 152, loss = 0.00680111
Iteration 153, loss = 0.00685248
Iteration 154, loss = 0.00701812
Iteration 155, loss = 0.00660595
Iteration 156, loss = 0.00638759
Iteration 157, loss = 0.00652481
Iteration 158, loss = 0.00647265
Iteration 159, loss = 0.00657403
Iteration 160, loss = 0.00685830
Iteration 161, loss = 0.00634332
Iteration 162, loss = 0.00641979
Iteration 163, loss = 0.00649235
Iteration 164, loss = 0.00631205
Iteration 165, loss = 0.00627229
Iteration 166, loss = 0.00636516
Iteration 167, loss = 0.00625442
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Output shape: (5, 5)
Surrogate saved